/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CadApproveDialog: typeof import('./src/components/dialogs/CadApproveDialog.vue')['default']
    CadChip: typeof import('./src/components/common/CadChip.vue')['default']
    CadCommunity: typeof import('./src/components/common/CadCommunity.vue')['default']
    CadDataTableCommunitiesApproved: typeof import('./src/components/dataTables/CadDataTableCommunitiesApproved.vue')['default']
    CadDataTableCommunitiesPending: typeof import('./src/components/dataTables/CadDataTableCommunitiesPending.vue')['default']
    CadDataTableCommunitiesRejected: typeof import('./src/components/dataTables/CadDataTableCommunitiesRejected.vue')['default']
    CadEmphasis: typeof import('./src/components/common/CadEmphasis.vue')['default']
    CadFooter: typeof import('./src/components/common/CadFooter.vue')['default']
    CadGlobalLoader: typeof import('./src/components/common/CadGlobalLoader.vue')['default']
    CadGoogleMaps: typeof import('./src/components/CadGoogleMaps.vue')['default']
    CadGridFAQ: typeof import('./src/components/CadGridFAQ.vue')['default']
    CadHero: typeof import('./src/components/CadHero.vue')['default']
    CadMapNumbers: typeof import('./src/components/CadMapNumbers.vue')['default']
    CadNav: typeof import('./src/components/common/CadNav.vue')['default']
    CadRejectDialog: typeof import('./src/components/dialogs/CadRejectDialog.vue')['default']
    CadRequestCorrectionsDialog: typeof import('./src/components/dialogs/CadRequestCorrectionsDialog.vue')['default']
    CadRequestReviewDialog: typeof import('./src/components/dialogs/CadRequestCorrectionsDialog.vue')['default']
    CadSetCensusStepDialog: typeof import('./src/components/dialogs/CadSetCensusStepDialog.vue')['default']
    CadSetOwnerDialog: typeof import('./src/components/dialogs/CadSetOwnerDialog.vue')['default']
    CadShare: typeof import('./src/components/common/CadShare.vue')['default']
    CadShowcase: typeof import('./src/components/CadShowcase.vue')['default']
    CadTableCommunity: typeof import('./src/components/dataTables/CadTableCommunity.vue')['default']
    CadUnderDevel: typeof import('./src/components/common/CadUnderDevel.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
