/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/AboutProject': RouteRecordInfo<'/AboutProject', '/AboutProject', Record<never, never>, Record<never, never>>,
    '/Community': RouteRecordInfo<'/Community', '/Community', Record<never, never>, Record<never, never>>,
    '/CommunityRegister': RouteRecordInfo<'/CommunityRegister', '/CommunityRegister', Record<never, never>, Record<never, never>>,
    '/dashboard/Community': RouteRecordInfo<'/dashboard/Community', '/dashboard/Community', Record<never, never>, Record<never, never>>,
    '/dashboard/Home': RouteRecordInfo<'/dashboard/Home', '/dashboard/Home', Record<never, never>, Record<never, never>>,
    '/dashboard/Profile': RouteRecordInfo<'/dashboard/Profile', '/dashboard/Profile', Record<never, never>, Record<never, never>>,
    '/gridFAQ/AboutCCIAO': RouteRecordInfo<'/gridFAQ/AboutCCIAO', '/gridFAQ/AboutCCIAO', Record<never, never>, Record<never, never>>,
    '/gridFAQ/GridFAQLanguages': RouteRecordInfo<'/gridFAQ/GridFAQLanguages', '/gridFAQ/GridFAQLanguages', Record<never, never>, Record<never, never>>,
    '/gridFAQ/GridFAQNations': RouteRecordInfo<'/gridFAQ/GridFAQNations', '/gridFAQ/GridFAQNations', Record<never, never>, Record<never, never>>,
    '/gridFAQ/GridFAQTraditionalCommunities': RouteRecordInfo<'/gridFAQ/GridFAQTraditionalCommunities', '/gridFAQ/GridFAQTraditionalCommunities', Record<never, never>, Record<never, never>>,
    '/Index': RouteRecordInfo<'/Index', '/Index', Record<never, never>, Record<never, never>>,
    '/Login': RouteRecordInfo<'/Login', '/Login', Record<never, never>, Record<never, never>>,
    '/Search': RouteRecordInfo<'/Search', '/Search', Record<never, never>, Record<never, never>>,
  }
}
